# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'hskim_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('regdate', models.DateTimeField(auto_created=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=200)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hskim_comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('regdate', models.DateTimeField(auto_created=True)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fk_category_id', models.ManyToManyField(to='hskimblog.Category')),
            ],
            options={
                'db_table': 'hskim_post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hskimblog.Post'),
        ),
    ]
