# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hskimblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
