# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public Post'), ('private', 'Private Post')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
