# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160604_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('opn', 'Open'), ('clsd', 'Closed'), ('prvt', 'Privated')], default='opn', max_length=20),
            preserve_default=False,
        ),
    ]
