# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160604_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('opn', 'Opened'), ('clsd', 'Closed'), ('prvt', 'Privated'), ('scheduled', '예약')], max_length=20),
        ),
    ]
