# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160610_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('public', 'Public Comment'), ('private', 'Private Comment')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public Post'), ('private', 'Private Post')], default='public', max_length=20),
        ),
    ]
