# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='제목없음', max_length=200),
        ),
    ]
